<a href="https://colab.research.google.com/github/rabikkk/Rabikk/blob/master/Matrix_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
my_matrix = np.matrix(np.random.rand(5, 3), dtype=np.float32) 
for i in my_matrix:
  print(i)

[[0.7184899  0.66424936 0.9373761 ]]
[[0.70627487 0.24526024 0.31322667]]
[[0.44956583 0.87317854 0.45888695]]
[[0.6145976 0.8331281 0.9929762]]
[[0.32790208 0.78581446 0.6742399 ]]


In [ ]:
import numpy 
import random 
my_matrix= numpy.empty([5, 3], dtype=float)
for i in range(5):
  for k in range(3):
         my_matrix= numpy.append (my_matrix, [random.uniform(-5, 5)])
for i in my_matrix:
  print(i)

-4.939008091088384
1.866480040514233
1.410849183944233
1.6397676838519493
0.9801379652684012
1.0934314357363153
4.765878910192914
3.4061032868366823
4.263575567519718
-2.4475513654641423
0.45913848354862985
-4.001756665293089
-4.771313236120919
-1.3697634451018126
4.294893147574912
0.8819023245581823
4.555446152491015
-0.0003339859629285513
2.1248154864852875
2.9669462015891437
-1.5940073356429796
0.883883257547275
-4.366771701941396
-0.7092399900940194
3.306205225941163
-4.240630066864824
-0.9046994628898926
3.753649453850901
-3.0588671650208763
1.6693263577872939


In [ ]:
import numpy 
my_matrix=numpy.random.uniform(-5, 5, size=(5, 3))
for i in my_matrix:
  print(i)

[ 1.93083482  2.22400364 -4.24404429]
[-2.80255397 -2.74836106 -0.49956321]
[-4.32221087  2.47396718  4.97175121]
[0.41595437 4.20905998 0.50829018]
[ 1.60459868  2.91341544 -4.338081  ]


In [ ]:
import numpy 
import random 
arr= numpy.empty([5, 3], dtype=float)
for i in range(5):
  for k in range(3):
     arr[i][k]=random.uniform(-5,5)
for i in arr:
  print(i)
  

[ 4.9811414  -3.91301434  1.80441199]
[0.80318626 1.16795241 0.60459693]
[ 0.65814996  4.51694023 -1.1533397 ]
[-3.52985562 -2.46150429  0.19577699]
[-3.54037191  1.89011436 -2.63145179]


In [ ]:
import numpy 
import random 
arr= numpy.empty([5, 3], dtype=float)
for i in range(5):
  for k in range(3):
     arr[i][k]=random.uniform(-5,5)
for i in arr:
  print(i)

[ 2.11465947 -1.36633565  4.12143024]
[ 0.92795633  3.97078644 -1.53516378]
[ 3.02783601  3.18342577 -2.42315378]
[-1.99058495  4.19841595 -3.60840531]
[-2.82450032  1.3120411  -2.92446896]
